kind: Service
apiVersion: v1
metadata:
  name: bring-service
spec:
  type: NodePort
  selector:
    app: bring-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30003

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bring-schedule-deployment
  labels:
    app: bring-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bring-schedule
      track: stable
  template:
    metadata:
      labels:
        app: bring-schedule
        track: stable
    spec:
      containers:
      - name: bring-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
